### ISSUE TITLE
Typed property FriendsOfHyperf\IdeHelper\Alias::$root must not be accessed before initialization

### ISSUE THREAD

**Issue by he426100** [friendsofhyperf/ide-helper#1]
一运行`php bin/hyperf.php ide-helper:model`就报错了  
```
$ php bin/hyperf.php ide-helper:model
Typed property FriendsOfHyperf\IdeHelper\Alias::$root must not be accessed before initialization
[ERROR] Error: Typed property FriendsOfHyperf\IdeHelper\Alias::$root must not be accessed before initialization in /workspaces/git/dc_api/vendor/friendsofhyperf/ide-helper/src/Alias.php:65
Stack trace:
#0 /workspaces/git/dc_api/vendor/friendsofhyperf/ide-helper/src/Eloquent.php(17): FriendsOfHyperf\IdeHelper\Alias->__construct('\\Hyperf\\DbConne...', '\\Eloquent')
#1 /workspaces/git/dc_api/vendor/friendsofhyperf/ide-helper/src/Command/ModelCommand.php(127): FriendsOfHyperf\IdeHelper\Eloquent::make()
#2 /workspaces/git/dc_api/vendor/friendsofhyperf/ide-helper/src/Command/ModelCommand.php(70): FriendsOfHyperf\IdeHelper\Command\ModelCommand->generateDocs(Array)
#3 /workspaces/git/dc_api/vendor/hyperf/command/src/Command.php(423): FriendsOfHyperf\IdeHelper\Command\ModelCommand->handle()
#4 [internal function]: Hyperf\Command\Command->Hyperf\Command\{closure}()
#5 {main}
```
当我试图修正这个报错的时候出来了更多的错误

php环境  
```
$ php -v
PHP 8.1.13 (cli) (built: Dec  6 2022 05:50:12) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.13, Copyright (c) Zend Technologies
    with Xdebug v3.2.0, Copyright (c) 2002-2022, by Derick Rethans
```

**Comment by huangdijia** [comment]
`composer r friendsofhyperf/ide-helper:^3.0.26 --dev` 再试试看。
